/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYBKGPDF
#define ROOSUSYBKGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkg2GaussiansPdf : public RooAbsPdf {
public:
  RooSUSYBkg2GaussiansPdf() {} ; 
  RooSUSYBkg2GaussiansPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _b1,
	      RooAbsReal& _b2);
  RooSUSYBkg2GaussiansPdf(const RooSUSYBkg2GaussiansPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkg2GaussiansPdf(*this,newname); }
  inline virtual ~RooSUSYBkg2GaussiansPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkg2GaussiansPdf,1) // Your description goes here...
};
 
#endif
