/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYBKGMBH2PDF
#define ROOSUSYBKGMBH2PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkgBH2Pdf : public RooAbsPdf {
public:
  RooSUSYBkgBH2Pdf() {} ; 
  RooSUSYBkgBH2Pdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _a3,
	      RooAbsReal& _a4);
  RooSUSYBkgBH2Pdf(const RooSUSYBkgBH2Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkgBH2Pdf(*this,newname); }
  inline virtual ~RooSUSYBkgBH2Pdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy a3 ;
  RooRealProxy a4 ;

  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkgBH2Pdf,1) // Your description goes here...
};
 
#endif
