/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYBKGMAPDF
#define ROOSUSYBKGMAPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkgMAPdf : public RooAbsPdf {
public:
  RooSUSYBkgMAPdf() {} ; 
  RooSUSYBkgMAPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _b1,
	      RooAbsReal& _b2,
	      RooAbsReal& _b3,
	      RooAbsReal& _b4,
	      RooAbsReal& _m1,
	      RooAbsReal& _m2);
  RooSUSYBkgMAPdf(const RooSUSYBkgMAPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkgMAPdf(*this,newname); }
  inline virtual ~RooSUSYBkgMAPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  RooRealProxy b3 ;
  RooRealProxy b4 ;
  RooRealProxy m1 ;
  RooRealProxy m2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkgMAPdf,1) // Your description goes here...
};
 
#endif
