/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYTPDF
#define ROOSUSYTPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYTPdf : public RooAbsPdf {
public:
  RooSUSYTPdf() {} ; 
  RooSUSYTPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _c,
	      RooAbsReal& _s,
	      RooAbsReal& _m0);
  RooSUSYTPdf(const RooSUSYTPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYTPdf(*this,newname); }
  inline virtual ~RooSUSYTPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy c ;
  RooRealProxy s ;
  RooRealProxy m0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYTPdf,1) // Your description goes here...
};
 
#endif
