 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooSUSYBkgBH2Pdf.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h"
 #include "TMath.h"

 ClassImp(RooSUSYBkgBH2Pdf) 

 RooSUSYBkgBH2Pdf::RooSUSYBkgBH2Pdf(const char *name, const char *title, 
                        RooAbsReal& _inv,
                        RooAbsReal& _a1,
                        RooAbsReal& _a2,
                        RooAbsReal& _a3,
                        RooAbsReal& _a4
                        ) :
   RooAbsPdf(name,title), 
   inv("inv","inv",this,_inv),
   a1("a1","a1",this,_a1),
   a2("a2","a2",this,_a2),
   a3("a3","a3",this,_a3),
   a4("a4","a4",this,_a4)
 { 
 } 


 RooSUSYBkgBH2Pdf::RooSUSYBkgBH2Pdf(const RooSUSYBkgBH2Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   inv("inv",this,other.inv),
   a1("a1",this,other.a1),
   a2("a2",this,other.a2),
   a3("a3",this,other.a3),
   a4("a4",this,other.a4)
 { 
 } 



 Double_t RooSUSYBkgBH2Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //~ return TMath::Power((inv+c2),a1+a2*inv)*TMath::Exp(-b1*(inv+c1));//+TMath::Power(inv,a2)*TMath::Exp(-b2*inv); 
   //~ return TMath::Power((1 - inv/13000*inv/13000),a2)/TMath::Power((inv/13000),(a3+a4*TMath::Log(inv/13000)));
   return a1/TMath::Power((inv*inv + a2*inv +a3),a4);
 } 



