/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYBKGPDF
#define ROOSUSYBKGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkgMoreGaussiansPdf : public RooAbsPdf {
public:
  RooSUSYBkgMoreGaussiansPdf() {} ; 
  RooSUSYBkgMoreGaussiansPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _a3,
	      RooAbsReal& _a4,
	      RooAbsReal& _b1,
	      RooAbsReal& _b2,
	      RooAbsReal& _b3,
	      RooAbsReal& _b4);
  RooSUSYBkgMoreGaussiansPdf(const RooSUSYBkgMoreGaussiansPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkgMoreGaussiansPdf(*this,newname); }
  inline virtual ~RooSUSYBkgMoreGaussiansPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy a3 ;
  RooRealProxy a4 ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  RooRealProxy b3 ;
  RooRealProxy b4 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkgMoreGaussiansPdf,1) // Your description goes here...
};
 
#endif
