/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYMOREPARAMSBKGPDF
#define ROOSUSYBKGMOREPARAMSPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkgMoreParamsPdf : public RooAbsPdf {
public:
  RooSUSYBkgMoreParamsPdf() {} ; 
  RooSUSYBkgMoreParamsPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _b1,
	      RooAbsReal& _b2,
	      RooAbsReal& _c1,
	      RooAbsReal& _c2);
  RooSUSYBkgMoreParamsPdf(const RooSUSYBkgMoreParamsPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkgMoreParamsPdf(*this,newname); }
  inline virtual ~RooSUSYBkgMoreParamsPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkgMoreParamsPdf,1) // Your description goes here...
};
 
#endif
