 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooSUSYX4Pdf.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 #include "TMath.h"

 ClassImp(RooSUSYX4Pdf) 

 RooSUSYX4Pdf::RooSUSYX4Pdf(const char *name, const char *title, 
                        RooAbsReal& _inv,
                        RooAbsReal& _c,
                        RooAbsReal& _s,
                        RooAbsReal& _m0) :
   RooAbsPdf(name,title), 
   inv("inv","inv",this,_inv),
   c("c","c",this,_c),
   s("s","s",this,_s),
   m0("m0","m0",this,_m0)
 { 
 } 


 RooSUSYX4Pdf::RooSUSYX4Pdf(const RooSUSYX4Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   inv("inv",this,other.inv),
   c("c",this,other.c),
   s("s",this,other.s),
   m0("m0",this,other.m0)
 { 
 } 



 Double_t RooSUSYX4Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
    //triangle
    Double_t value = c*((inv*inv*inv*inv)*TMath::Sqrt(TMath::Pi())*(TMath::Erf(inv/(TMath::Sqrt(2)*s))+TMath::Erf((m0-inv)/(TMath::Sqrt(2)*s))));

    if(value>0) return value;
    else return 0.;
    
 } 



