/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYPDF
#define ROOSUSYXM4PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYXM4Pdf : public RooAbsPdf {
public:
  RooSUSYXM4Pdf() {} ; 
  RooSUSYXM4Pdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _c,
	      RooAbsReal& _s,
	      RooAbsReal& _m0);
  RooSUSYXM4Pdf(const RooSUSYXM4Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYXM4Pdf(*this,newname); }
  inline virtual ~RooSUSYXM4Pdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy c ;
  RooRealProxy s ;
  RooRealProxy m0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYXM4Pdf,1) // Your description goes here...
};
 
#endif
