/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSUSYBKGPDF
#define ROOSUSYBKGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSUSYBkgPdf : public RooAbsPdf {
public:
  RooSUSYBkgPdf() {} ; 
  RooSUSYBkgPdf(const char *name, const char *title,
	      RooAbsReal& _inv,
	      RooAbsReal& _a1,
	      RooAbsReal& _a2,
	      RooAbsReal& _b1,
	      //~ RooAbsReal& _b2,
	      //~ RooAbsReal& _c1,
	      //~ RooAbsReal& _c2);
	      RooAbsReal& _b2);
  RooSUSYBkgPdf(const RooSUSYBkgPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSUSYBkgPdf(*this,newname); }
  inline virtual ~RooSUSYBkgPdf() { }

protected:

  RooRealProxy inv ;
  RooRealProxy a1 ;
  RooRealProxy a2 ;
  RooRealProxy b1 ;
  RooRealProxy b2 ;
  //~ RooRealProxy c1 ;
  //~ RooRealProxy c2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSUSYBkgPdf,1) // Your description goes here...
};
 
#endif
